services:
  ejecucion_proyecto:
    container_name: proyecto_seguridad
    volumes:
      - ./resultados:/resultados
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["bash", "/entry.sh"]
    env_file:
      - .env